source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'middleman-livereload'
gem 'middleman-webpack'
gem 'sass', '~> 3.4', '>= 3.4.22'
gem 'compass', '~> 1.0', '>= 1.0.3'
